# Catppuccin-mocha Wezterm colour
# See: https://github.com/catppuccin/wezterm/blob/main/plugin/init.lua
#rosewater = "#f5e0dc",
#flamingo = "#f2cdcd",
#pink = "#f5c2e7",
#mauve = "#cba6f7",
#red = "#f38ba8",
#maroon = "#eba0ac",
#peach = "#fab387",
#yellow = "#f9e2af",
#green = "#a6e3a1",
#teal = "#94e2d5",
#sky = "#89dceb",
#sapphire = "#74c7ec",
#blue = "#89b4fa",
#lavender = "#b4befe",
#text = "#cdd6f4",
#text = "#cdd6f4",
#subtext1 = "#bac2de",
#subtext0 = "#a6adc8",
#overlay2 = "#9399b2",
#overlay1 = "#7f849c",
#overlay0 = "#6c7086",
#surface2 = "#585b70",
#surface1 = "#45475a",
#surface0 = "#313244",
#base = "#1e1e2e",
#mantle = "#181825",
#crust = "#11111b",

format = """
$hostname\
[](fg:#1E1E2E bg:#89dceb)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:none)\
\n$kubenetes$character"""

[character]
vimcmd_symbol = "[❮](bold purple)"

[directory]
read_only = " 󰌾"
style = "fg:#e3e5e5 bg:#45475a"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"~" = ""

[git_branch]
symbol = " "
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[hostname]
ssh_only = false
style = "fg:#BAC2DE bg:#1E1E2E"
format = '[$ssh_symbol ](bold blue)[$hostname]($style)'
disabled = false

[kubernetes]
disabled = false

