[[bundle]]
name = "junegunn/fzf"

[[bundle]]
name = "neovim/neovim"
bin = "nvim$"

[[bundle]]
name = "eza-community/eza"
arch = "x86_64"

# [[bundle]]
# name = "zellij"
# source = "zellij-org/zellij"
# arch = "x86_64"
